# Generated by Django 4.2.20 on 2025-05-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Antenna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tower_id", models.IntegerField(unique=True)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("radius", models.FloatField()),
            ],
        ),
    ]
