# Generated by Django 4.2.20 on 2025-05-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antenna",
            name="radius",
            field=models.FloatField(help_text="Coverage radius in meters"),
        ),
    ]
