# Generated by Django 4.2.20 on 2025-05-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0002_alter_antenna_radius"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antenna",
            name="radius",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="antenna",
            name="tower_id",
            field=models.IntegerField(),
        ),
    ]
